/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesIndexRouteImport } from './routes/features/index'
import { Route as CountriesIndexRouteImport } from './routes/countries/index'
import { Route as CarsIndexRouteImport } from './routes/cars/index'
import { Route as BrandsIndexRouteImport } from './routes/brands/index'
import { Route as FeaturesCreateRouteImport } from './routes/features/create'
import { Route as FeaturesFeatureIdRouteImport } from './routes/features/$featureId'
import { Route as CountriesCreateRouteImport } from './routes/countries/create'
import { Route as CountriesCountryIdRouteImport } from './routes/countries/$countryId'
import { Route as CarsCreateRouteImport } from './routes/cars/create'
import { Route as CarsCarIdRouteImport } from './routes/cars/$carId'
import { Route as BrandsCreateRouteImport } from './routes/brands/create'
import { Route as BrandsBrandIdRouteImport } from './routes/brands/$brandId'
import { Route as CarsCarIdPhotosRouteImport } from './routes/cars/$carId_.photos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesCreateRoute = FeaturesCreateRouteImport.update({
  id: '/features/create',
  path: '/features/create',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesFeatureIdRoute = FeaturesFeatureIdRouteImport.update({
  id: '/features/$featureId',
  path: '/features/$featureId',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCreateRoute = CountriesCreateRouteImport.update({
  id: '/countries/create',
  path: '/countries/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCountryIdRoute = CountriesCountryIdRouteImport.update({
  id: '/countries/$countryId',
  path: '/countries/$countryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsCreateRoute = CarsCreateRouteImport.update({
  id: '/cars/create',
  path: '/cars/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsCarIdRoute = CarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsCreateRoute = BrandsCreateRouteImport.update({
  id: '/brands/create',
  path: '/brands/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsCarIdPhotosRoute = CarsCarIdPhotosRouteImport.update({
  id: '/cars/$carId_/photos',
  path: '/cars/$carId/photos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/create': typeof BrandsCreateRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/cars/create': typeof CarsCreateRoute
  '/countries/$countryId': typeof CountriesCountryIdRoute
  '/countries/create': typeof CountriesCreateRoute
  '/features/$featureId': typeof FeaturesFeatureIdRoute
  '/features/create': typeof FeaturesCreateRoute
  '/brands/': typeof BrandsIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/cars/$carId/photos': typeof CarsCarIdPhotosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/create': typeof BrandsCreateRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/cars/create': typeof CarsCreateRoute
  '/countries/$countryId': typeof CountriesCountryIdRoute
  '/countries/create': typeof CountriesCreateRoute
  '/features/$featureId': typeof FeaturesFeatureIdRoute
  '/features/create': typeof FeaturesCreateRoute
  '/brands': typeof BrandsIndexRoute
  '/cars': typeof CarsIndexRoute
  '/countries': typeof CountriesIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/cars/$carId/photos': typeof CarsCarIdPhotosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/brands/create': typeof BrandsCreateRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/cars/create': typeof CarsCreateRoute
  '/countries/$countryId': typeof CountriesCountryIdRoute
  '/countries/create': typeof CountriesCreateRoute
  '/features/$featureId': typeof FeaturesFeatureIdRoute
  '/features/create': typeof FeaturesCreateRoute
  '/brands/': typeof BrandsIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/cars/$carId_/photos': typeof CarsCarIdPhotosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands/$brandId'
    | '/brands/create'
    | '/cars/$carId'
    | '/cars/create'
    | '/countries/$countryId'
    | '/countries/create'
    | '/features/$featureId'
    | '/features/create'
    | '/brands/'
    | '/cars/'
    | '/countries/'
    | '/features/'
    | '/cars/$carId/photos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands/$brandId'
    | '/brands/create'
    | '/cars/$carId'
    | '/cars/create'
    | '/countries/$countryId'
    | '/countries/create'
    | '/features/$featureId'
    | '/features/create'
    | '/brands'
    | '/cars'
    | '/countries'
    | '/features'
    | '/cars/$carId/photos'
  id:
    | '__root__'
    | '/'
    | '/brands/$brandId'
    | '/brands/create'
    | '/cars/$carId'
    | '/cars/create'
    | '/countries/$countryId'
    | '/countries/create'
    | '/features/$featureId'
    | '/features/create'
    | '/brands/'
    | '/cars/'
    | '/countries/'
    | '/features/'
    | '/cars/$carId_/photos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRoute
  BrandsCreateRoute: typeof BrandsCreateRoute
  CarsCarIdRoute: typeof CarsCarIdRoute
  CarsCreateRoute: typeof CarsCreateRoute
  CountriesCountryIdRoute: typeof CountriesCountryIdRoute
  CountriesCreateRoute: typeof CountriesCreateRoute
  FeaturesFeatureIdRoute: typeof FeaturesFeatureIdRoute
  FeaturesCreateRoute: typeof FeaturesCreateRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  CarsIndexRoute: typeof CarsIndexRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  CarsCarIdPhotosRoute: typeof CarsCarIdPhotosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/create': {
      id: '/features/create'
      path: '/features/create'
      fullPath: '/features/create'
      preLoaderRoute: typeof FeaturesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$featureId': {
      id: '/features/$featureId'
      path: '/features/$featureId'
      fullPath: '/features/$featureId'
      preLoaderRoute: typeof FeaturesFeatureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/create': {
      id: '/countries/create'
      path: '/countries/create'
      fullPath: '/countries/create'
      preLoaderRoute: typeof CountriesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$countryId': {
      id: '/countries/$countryId'
      path: '/countries/$countryId'
      fullPath: '/countries/$countryId'
      preLoaderRoute: typeof CountriesCountryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/create': {
      id: '/cars/create'
      path: '/cars/create'
      fullPath: '/cars/create'
      preLoaderRoute: typeof CarsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$carId': {
      id: '/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof CarsCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/create': {
      id: '/brands/create'
      path: '/brands/create'
      fullPath: '/brands/create'
      preLoaderRoute: typeof BrandsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$carId_/photos': {
      id: '/cars/$carId_/photos'
      path: '/cars/$carId/photos'
      fullPath: '/cars/$carId/photos'
      preLoaderRoute: typeof CarsCarIdPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsBrandIdRoute: BrandsBrandIdRoute,
  BrandsCreateRoute: BrandsCreateRoute,
  CarsCarIdRoute: CarsCarIdRoute,
  CarsCreateRoute: CarsCreateRoute,
  CountriesCountryIdRoute: CountriesCountryIdRoute,
  CountriesCreateRoute: CountriesCreateRoute,
  FeaturesFeatureIdRoute: FeaturesFeatureIdRoute,
  FeaturesCreateRoute: FeaturesCreateRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  CarsIndexRoute: CarsIndexRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  CarsCarIdPhotosRoute: CarsCarIdPhotosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
